### ISSUE TITLE
Redis connection with password for RSMQ Python

### ISSUE THREAD

**Issue by brnavneet** [mlasevich/PyRSMQ#15]
Currently, the Latest version 0.4.3 RSMQ Python does not allow Redis Password as an argument.

Could you please fix it or Kindly let me know where I can Do it?

**Comment by mlasevich** [comment]
Duplicate #2 

There is an `options` field that is designed for any option supported by RedisPy client to be passed to it. Password field can be one of those options. If you wish to use a different (compatible) client, you can also pass that in configured however you want

example:

```python

consumer = RedisSMQConsumer('my-queue', processor, host='127.0.0.1', options={"password": "mypassword"})

```

**Comment by brnavneet** [comment]
Thanks a lot! it works. But It would be better to mention it in the document as an example.
