### ISSUE TITLE
typo in `setCient` method

### ISSUE THREAD

**Issue by JosXa** [mlasevich/PyRSMQ#3]
Looks like `setCient` is supposed to be named `setClient`.

**Comment by mlasevich** [comment]
Ugh, how has no one noticed this after over a year  :-/ 

Thanks.

**Comment by mlasevich** [comment]
Pushed a fix, Travis is being wonky, not building. As soon as it recovers, should be released as v0.4.2

**Comment by mlasevich** [comment]
v0.4.2 released

**Comment by JosXa** [comment]
Maintainer is a busy beaver ^^ thanks, nice!
